# Generated by Django 5.2.6 on 2025-09-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cover_letter',
        ),
    ]
